#!/usr/bin/env node
/**
 * Regenerate app.yaml from databricks.yml bundle variables.
 *
 * databricks.yml is the single source of truth for environment parameters.
 * The Apps platform reads env vars from app.yaml, which does NOT support
 * ${var...} substitution — so this script renders app.yaml from the bundle
 * variables of the chosen target (default: the target marked `default: true`).
 *
 * Usage:
 *   node tools/render_app_yaml.mjs            # default target
 *   node tools/render_app_yaml.mjs -t staging
 *   npm run render:appyaml
 *
 * Run this after editing databricks.yml, before `databricks bundle deploy`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/** env entries that reference bundle-managed app resources (kept as valueFrom). */
const RESOURCE_ENV = [
  ['DATABRICKS_SERVING_ENDPOINT_NAME', 'agents-serving-endpoint'],
  ['EMBEDDING_ENDPOINT_NAME', 'embedding-endpoint'],
  ['LAKEBASE_ENDPOINT', 'postgres'],
  ['DATABRICKS_WAREHOUSE_ID', 'sql-warehouse'],
];

/** env entries rendered from bundle variables (literal values). */
const VAR_ENV = [
  ['COFFEE_CATALOG', 'catalog'],
  ['COFFEE_SCHEMA', 'schema'],
  ['LAKEBASE_PROJECT', 'postgres_project'],
  ['GENIE_SPACE_ID', 'genie_space_id'],
];

const argv = process.argv.slice(2);
const targetName = argv[argv.indexOf('-t') + 1] ?? null;

const bundle = YAML.parse(readFileSync(join(ROOT, 'databricks.yml'), 'utf8'));
const targets = bundle.targets ?? {};
const target = targetName
  ? targets[targetName]
  : Object.values(targets).find((t) => t?.default);
if (!target) {
  console.error(`target ${targetName ?? '(default)'} not found in databricks.yml`);
  process.exit(1);
}
const variables = target.variables ?? {};

const lines = [
  '# GENERATED by tools/render_app_yaml.mjs from databricks.yml — do not edit by hand.',
  '# databricks.yml の variables が単一ソース。変更したら同スクリプトで再生成すること。',
  "command: ['npm', 'run', 'start']",
  'env:',
];
for (const [envName, resource] of RESOURCE_ENV) {
  lines.push(`  - name: ${envName}`, `    valueFrom: ${resource}`);
}
for (const [envName, varKey] of VAR_ENV) {
  lines.push(`  - name: ${envName}`, `    value: '${variables[varKey] ?? ''}'`);
}

writeFileSync(join(ROOT, 'app.yaml'), lines.join('\n') + '\n');
console.log(`wrote app.yaml (target: ${targetName ?? 'default'})`);
for (const [envName, varKey] of VAR_ENV) {
  console.log(`  ${envName} = '${variables[varKey] ?? ''}'`);
}
